version: '3.8'
services:
  fileorganizer:
    build: .
    image: fileorganizer:latest
    container_name: fileorganizer
    volumes:
      - /home/source-test:/data/source:rw
      - /media/destinationDir:/data/dest:rw
    environment:
      SOURCE_DIR: "/data/source"
      DEST_DIR: "/data/dest"
      MODE: "move"
      EMAIL: "jono1408@gmail.com"
      SMTP_HOST: "smtp.gmail.com"
      SMTP_PORT: "587"
      SMTP_USER: "jono.xenothreat@gmail.com"
      SMTP_PASSWORD: "zakzcbfnmgwyvsux"
      SMTP_USE_TLS: "true"
      SCHEDULE: "300"
    restart: unless-stopped
